[package]
name = "tfhe-aes"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { git = "https://github.com/zama-ai/tfhe-rs.git", rev = "38a7e4f", features = ["boolean", "shortint", "integer", "x86_64"]}
aes = "0.8.0"


